# Generated by Django 5.0.6 on 2024-06-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boking_date',
            new_name='booking_date',
        ),
    ]
